### ISSUE TITLE
Incorrect OpenAPI element names

### ISSUE THREAD

**Issue by endafarrell** [endafarrell/sanic-openapi3e#9]
All of these names are incorrect:

```
        authorization_code:
          authorization_url: authorization_url
          token_url: token_url
          scopes:
            scope1: ''
            scope2: ''
      openid_connect_url: n/a
```
